services:
  asa-server-${SERVER_NAME}:
    container_name: asa-server-${CONTAINER_NAME}
    hostname: asa-server-${HOST_NAME}
    entrypoint: "/usr/bin/start_server"
    user: gameserver
    image: "mschnitzer/asa-linux-server:1.4.1"
    tty: true
    environment:
      ASA_START_PARAMS: "${MAP}?listen?Port=${LISTEN_PORT}?RCONPort=${RCON_PORT}?RCONEnabled=True -WinLiveMaxPlayers=${PLAYER_COUNT} -mods=${MOD_LIST} -clusterid=${CLUSTER_ID} -ClusterDirOverride=\"/home/gameserver/cluster-shared\""
      ENABLE_DEBUG: "0"
    ports:
      - "${LISTEN_PORT}:${LISTEN_PORT}/udp"
      - "${RCON_PORT}:${RCON_PORT}/tcp"
    volumes:
      - "/home/ubuntu/steam-${CONTAINER_NAME}:/home/gameserver/Steam:rw"
      - "/home/ubuntu/steamcmd-${CONTAINER_NAME}:/home/gameserver/steamcmd:rw"
      - "/home/ubuntu/server-files-${CONTAINER_NAME}:/home/gameserver/server-files:rw"
      - "/srv/ark_cluster:/home/gameserver/cluster-shared:rw"
      - "/etc/localtime:/etc/localtime:ro"
    networks:
      - asa-network

networks:
  asa-network:
    attachable: true
    driver: bridge
    driver_opts:
      com.docker.network.bridge.name: 'asanet'
