---
# services:
#   asa-server-theisland:
#     container_name: asa-server-theisland
#     hostname: asa-server-theisland
#     entrypoint: "/usr/bin/start_server"
#     user: gameserver
#     image: "mschnitzer/asa-linux-server:1.4.1"
#     tty: true
#     environment:
#       - ASA_START_PARAMS=TheIsland_WP?listen?Port=7777?RCONPort=27020?RCONEnabled=True -WinLiveMaxPlayers=50 -mods=1065717, 986540, 929578, 1133222, 930442, 947733, 1066017, 948965, 940786, 1122696, 1019389, 970540, 935528, 928548, 933099, 929838, 929868, 931874, 1063373, 928501, 939055, 1004535, 974884, 929420, 912815, 1201667, 1058624, 953108, 1180638, 930374, 967547, 1123428, 933301 -clusterid=my-secret-id -ClusterDirOverride="/home/gameserver/cluster-shared"
#       - ENABLE_DEBUG=0
#     ports:
#       - 7777:7777/udp
#       - 27020:27020/tcp
#     volumes:
#       - /home/ubuntu/steam-theisland:/home/gameserver/Steam:rw
#       - /home/ubuntu/steamcmd-theisland:/home/gameserver/steamcmd:rw
#       - /home/ubuntu/server-files-theisland:/home/gameserver/server-files:rw
#       - /srv/ark_cluster:/home/gameserver/cluster-shared:rw
#       - /etc/localtime:/etc/localtime:ro
#     networks:
#       - asa-network

# networks:
#   asa-network:
#     attachable: true
#     driver: bridge
#     driver_opts:
#       com.docker.network.bridge.name: 'asanet'

services:
  asa-server-theisland:
    container_name: asa-server-theisland
    hostname: asa-server-theisland
    entrypoint: "/usr/bin/start_server"
    user: gameserver
    image: "mschnitzer/asa-linux-server:1.4.1"
    tty: true
    environment:
      - >-
        ASA_START_PARAMS=TheIsland_WP?listen?Port=7777?RCONPort=27020?RCONEnabled=True
        -WinLiveMaxPlayers=50
        -mods=1065717,986540,929578,1133222,930442,947733,1066017,
              948965,940786,1122696,1019389,970540,935528,928548,933099,
              929838,929868,931874,1063373,928501,939055,1004535,974884,
              929420,912815,1201667,1058624,953108,1180638,930374,967547,
              1123428,933301
        -clusterid=my-secret-id
        -ClusterDirOverride="/home/gameserver/cluster-shared"
      - ENABLE_DEBUG=0
    ports:
      - 7777:7777/udp
      - 27020:27020/tcp
    volumes:
      - /home/ubuntu/steam-theisland:/home/gameserver/Steam:rw
      - /home/ubuntu/steamcmd-theisland:/home/gameserver/steamcmd:rw
      - /home/ubuntu/server-files-theisland:/home/gameserver/server-files:rw
      - /srv/ark_cluster:/home/gameserver/cluster-shared:rw
      - /etc/localtime:/etc/localtime:ro
    networks:
      - asa-network

networks:
  asa-network:
    attachable: true
    driver: bridge
    driver_opts:
      com.docker.network.bridge.name: 'asanet'

