---
services:
  asa-server-astraeos:
    container_name: asa-server-astraeos
    hostname: asa-server-astraeos
    entrypoint: "/usr/bin/start_server"
    user: gameserver
    image: "mschnitzer/asa-linux-server:1.4.1"
    tty: true
    environment:
      - ASA_START_PARAMS=Astraeos_WP?listen?Port=7777?RCONPort=27020?RCONEnabled=True -WinLiveMaxPlayers=50 -clusterid=my-secret-id -ClusterDirOverride="/home/gameserver/cluster-shared"
      - ENABLE_DEBUG=0
    ports:
      - 7778:7777/udp
      - 27021:27020/tcp
    volumes:
      - /home/ubuntu/steam-astraeos:/home/gameserver/Steam:rw
      - /home/ubuntu/steamcmd-astraeos:/home/gameserver/steamcmd:rw
      - /home/ubuntu/server-files-astraeos:/home/gameserver/server-files:rw
      - /srv/ark_cluster:/home/gameserver/cluster-shared:rw
      - /etc/localtime:/etc/localtime:ro
    networks:
      - asa-network

networks:
  asa-network:
    attachable: true
    driver: bridge
    driver_opts:
      com.docker.network.bridge.name: 'asanet'