---
services:
  asa-server:
    container_name: asa-server-necrotic-dominion
    hostname: asa-server-necrotic-dominion
    entrypoint: "/usr/bin/start_server"
    user: gameserver
    image: "mschnitzer/asa-linux-server:1.4.1"
    tty: true
    environment:
      - >-
        ASA_START_PARAMS=LichKing_WP?listen?Port=7778?RCONPort=27021?RCONEnabled=True
        -WinLiveMaxPlayers=50
        -mods=1117983,1065717,986540,929578,1133222,930442,947733,1066017,948965,940786,1122696,1019389,970540,935528,928548,942024,929838,929868,931874,1063373,928501,939055,1004535,974884,929420,912815,1201667,1058624,953108,1180638,930374,967547,1123428,933301,1252684
        -clusterid=USARoleplay
        -clusterid=USARoleplay
        -ClusterDirOverride="/home/gameserver/cluster-shared"
      - ENABLE_DEBUG=0
    ports:
      - 7778:7777/udp
      - 27021:27020/tcp
    depends_on:
      - set-permissions-1
    volumes:
      - steam-2:/home/gameserver/Steam:rw
      - steamcmd-2:/home/gameserver/steamcmd:rw
      - server-files-2:/home/gameserver/server-files:rw
      - /mnt/ark_cluster:/home/gameserver/cluster-shared:rw
      - /etc/localtime:/etc/localtime:ro
    networks:
      - asa-network # end of helth check option. remove if this doesn't work
    restart: unless-stopped

  set-permissions-1:
    container_name: fix-perms-svartalfheim
    image: "alpine:latest"
    entrypoint: >
      /bin/sh -c "
      chown -R 25000:25000 /steam &&
      chown -R 25000:25000 /steamcmd &&
      chown -R 25000:25000 /server-files &&
      chown -R 25000:25000 /cluster-shared"
    user: root
    volumes:
      - steam-2:/steam:rw
      - steamcmd-2:/steamcmd:rw
      - server-files-2:/server-files:rw
      - /mnt/ark_cluster:/cluster-shared:rw

volumes:
  steam-2:
  steamcmd-2:
  server-files-2:

networks:
  asa-network:
    attachable: true
    driver: bridge
    driver_opts:
      com.docker.network.bridge.name: 'asanet'
