name: ASA Settings Apply (manual config changes)

on:
  push:
    branches: [ main ]
    paths:
      - 'ASA/**/GameUserSettings.ini'
      - 'ASA/**/Game.ini'
  workflow_dispatch:

permissions:
  contents: write
  pull-requests: write

# Allow multiple runs in parallel; don’t coalesce runs
concurrency:
  group: asa-settings-apply-${{ github.run_id }}
  cancel-in-progress: false

env:
  # waits (set to 30s for testing; bump for prod)
  WAIT_30M: "30"      # prod: 900
  WAIT_15M: "30"      # prod: 720
  WAIT_3M:  "30"      # prod: 180

  LOG_READY_TIMEOUT:  "600"   # 10m
  RCON_READY_TIMEOUT: "1200"  # 20m

jobs:
  build-matrix:
    # If the merge commit title contains our bot marker, skip the whole workflow.
    if: ${{ !contains(github.event.head_commit.message, '[auto-gus-sync]') }}
    runs-on: self-hosted
    outputs:
      matrix: ${{ steps.mk-matrix.outputs.matrix }}

    steps:
      - name: Checkout
        uses: actions/checkout@v5
        with:
          fetch-depth: 0

      # Compute changed *.ini files across the whole push range
      - name: Compute changed ini files (range-aware)
        id: changed_range
        shell: bash
        run: |
          set -euo pipefail
          BEFORE="${{ github.event.before }}"
          AFTER="${{ github.sha }}"

          if [ -z "${BEFORE}" ] || ! git cat-file -e "${BEFORE}^{commit}" 2>/dev/null; then
            BEFORE="$(git rev-parse HEAD~1)"
          fi

          git --no-pager diff --name-only "${BEFORE}" "${AFTER}" \
            -- 'ASA/**/GameUserSettings.ini' 'ASA/**/Game.ini' > changed.txt || true
          echo "Changed INI files:"
          cat changed.txt || true

          {
            echo "list<<EOF"
            cat changed.txt
            echo "EOF"
          } >> "$GITHUB_OUTPUT"

      # Map changed files -> targets (from deploy/targets.json)
      - name: Build matrix from deploy/targets.json
        id: mk-matrix
        uses: actions/github-script@v7
        env:
          CHANGED_LIST: ${{ steps.changed_range.outputs.list }}
        with:
          script: |
            const fs = require('fs');
            const manifest = JSON.parse(fs.readFileSync('deploy/targets.json','utf8'));
            const changed = (process.env.CHANGED_LIST || '')
              .split('\n').map(s => s.trim()).filter(Boolean);

            // For each target, detect which of its two ini files changed.
            const picks = [];
            for (const t of manifest.targets) {
              const base = t.work_subdir.replace(/\/+$/,'');
              const gusPath  = `${base}/GameUserSettings.ini`;
              const gamePath = `${base}/Game.ini`;
              const apply_gus  = changed.includes(gusPath);
              const apply_game = changed.includes(gamePath);
              if (apply_gus || apply_game) {
                picks.push({
                  ...t,
                  apply_gus,
                  apply_game
                });
              }
            }

            // de-dupe by id just to be safe
            const uniq = Object.values(Object.fromEntries(picks.map(t => [t.id, t])));
            core.info(`Changed files: ${changed.join(', ') || '(none)'}`);
            core.info(`Selected targets: ${uniq.map(t => `${t.id}[gus:${t.apply_gus}/game:${t.apply_game}]`).join(', ') || '(none)'}`);
            core.setOutput('matrix', JSON.stringify(uniq));

  apply:
    needs: build-matrix
    if: ${{ needs.build-matrix.outputs.matrix != '[]' }}
    runs-on: self-hosted

    # Queue per physical host (no cancellations); different hosts still run in parallel
    environment:
      name: host-${{ matrix.ssh_host_secret }}

    strategy:
      fail-fast: false
      matrix:
        include: ${{ fromJSON(needs.build-matrix.outputs.matrix) }}

    env:
      SSH_USER: ${{ secrets.ASA_SERVER_SSH_USER }}
      SSH_PORT: ${{ secrets.ASA_SERVER_PORT }}
      HOST: ${{ secrets[matrix.ssh_host_secret] }}
      WORK_DIR: ${{ secrets.WORK_DIR }}

      REPO_SUBDIR: ${{ matrix.work_subdir }}
      CNAME: ${{ matrix.container }}
      LIVE_WIN_DIR: /var/lib/docker/volumes/${{ matrix.volume }}/_data/ShooterGame/Saved/Config/WindowsServer
      APPLY_GUS: ${{ matrix.apply_gus }}
      APPLY_GAME: ${{ matrix.apply_game }}

    steps:
      - name: Mint GitHub App token
        id: app
        uses: actions/create-github-app-token@v2
        with:
          app-id: ${{ secrets.APP_ID }}
          private-key: ${{ secrets.APP_PRIVATE_KEY }}

      - name: Checkout (for host update)
        uses: actions/checkout@v5
        with:
          fetch-depth: 0
          token: ${{ steps.app.outputs.token }}

      - name: Setup SSH
        uses: webfactory/ssh-agent@v0.9.1
        with:
          ssh-private-key: ${{ secrets.ASA_SERVERS_PRIVATE_KEY }}

      # --- Drain & stop (same cadence as compose deploy) ---
      - name: RCON 30m warning
        run: |
          ssh -o StrictHostKeyChecking=no -p "$SSH_PORT" "$SSH_USER@$HOST" \
            "sudo docker exec '$CNAME' asa-ctrl rcon --exec \"serverchat Server updating settings in 30 minutes\""

      - name: Wait 15m
        run: sleep ${{ env.WAIT_30M }}

      - name: RCON 15m warning
        run: |
          ssh -o StrictHostKeyChecking=no -p "$SSH_PORT" "$SSH_USER@$HOST" \
            "sudo docker exec '$CNAME' asa-ctrl rcon --exec \"serverchat Server updating settings in 15 minutes\""

      - name: Wait 12m
        run: sleep ${{ env.WAIT_15M }}

      - name: RCON 3m warning
        run: |
          ssh -o StrictHostKeyChecking=no -p "$SSH_PORT" "$SSH_USER@$HOST" \
            "sudo docker exec '$CNAME' asa-ctrl rcon --exec \"serverchat Server updating settings in 3 minutes. Final warning!\""

      - name: Wait 3m
        run: sleep ${{ env.WAIT_3M }}

      - name: Saveworld & shutdown announce
        run: |
          ssh -o StrictHostKeyChecking=no -p "$SSH_PORT" "$SSH_USER@$HOST" \
            "sudo docker exec '$CNAME' asa-ctrl rcon --exec \"serverchat Saving world and shutting down for settings update.\" && \
             sudo docker exec '$CNAME' asa-ctrl rcon --exec \"saveworld\""

      - name: Stop container
        run: |
          ssh -o StrictHostKeyChecking=no -p "$SSH_PORT" "$SSH_USER@$HOST" \
            "cd '$WORK_DIR/$REPO_SUBDIR' && sudo docker compose down"

      # --- Update host checkout (to main) ---
      - name: Update host checkout to origin/main
        run: |
          ssh -o StrictHostKeyChecking=no -p "$SSH_PORT" "$SSH_USER@$HOST" << 'EOF'
          set -euo pipefail
          cd "${{ env.WORK_DIR }}/${{ env.REPO_SUBDIR }}"
          TOKEN='${{ steps.app.outputs.token }}'
          REPO_SLUG='${{ github.repository }}'
          REPO_URL="https://x-access-token:${TOKEN}@github.com/${REPO_SLUG}.git"
          GIT_TERMINAL_PROMPT=0 git fetch --no-tags --prune "$REPO_URL" main
          git reset --hard FETCH_HEAD
          EOF

      # --- Apply changed files only ---
      - name: Apply GameUserSettings.ini / Game.ini to live (only if changed)
        run: |
          ssh -o StrictHostKeyChecking=no -p "$SSH_PORT" "$SSH_USER@$HOST" << 'EOF'
          set -euo pipefail
          cd "${{ env.WORK_DIR }}/${{ env.REPO_SUBDIR }}"

          LIVE="${{ env.LIVE_WIN_DIR }}"

          # Only touch the files that actually changed in the PR/merge
          if [ "${{ env.APPLY_GUS }}" = "true" ]; then
            # Inject admin password placeholder with secret, then copy
            sed -i "s/\${SERVER_PASSWORD}/${{ secrets.ASA_ADMIN_SECRET }}/g" GameUserSettings.ini
            sudo install -m 0644 -o root -g root GameUserSettings.ini "${LIVE}/GameUserSettings.ini"
          fi

          if [ "${{ env.APPLY_GAME }}" = "true" ]; then
            sudo install -m 0644 -o root -g root Game.ini "${LIVE}/Game.ini"
          fi
          EOF

      - name: Start container
        run: |
          ssh -o StrictHostKeyChecking=no -p "$SSH_PORT" "$SSH_USER@$HOST" \
            "cd '$WORK_DIR/$REPO_SUBDIR' && sudo docker compose up -d"

      # --- Readiness gates (same as compose deploy) ---
      - name: Wait for startup log ("Starting the ARK...")
        run: |
          ssh -o StrictHostKeyChecking=no -p "$SSH_PORT" "$SSH_USER@$HOST" << 'EOF'
          set -euo pipefail
          CNAME='${{ env.CNAME }}'
          end=$((SECONDS+${{ env.LOG_READY_TIMEOUT }}))
          until sudo docker logs --tail 500 "$CNAME" 2>&1 | grep -q "Starting the ARK: Survival Ascended dedicated server"; do
            if [ $SECONDS -gt $end ]; then
              echo "Timed out waiting for startup log." >&2
              sudo docker logs "$CNAME" --tail 200 >&2 || true
              exit 1
            fi
            sleep 5
          done
          echo "Startup log observed."
          EOF

      - name: Wait for RCON to respond
        run: |
          ssh -o StrictHostKeyChecking=no -p "$SSH_PORT" "$SSH_USER@$HOST" << 'EOF'
          set -euo pipefail
          CNAME='${{ env.CNAME }}'
          end=$((SECONDS+${{ env.RCON_READY_TIMEOUT }}))
          while :; do
            if sudo docker exec "$CNAME" asa-ctrl rcon --exec "listplayers" >/dev/null 2>&1 \
               || sudo docker exec "$CNAME" asa-ctrl rcon --exec "serverchat healthcheck" >/dev/null 2>&1; then
              echo "RCON is responsive."
              break
            fi
            if [ $SECONDS -gt $end ]; then
              echo "Timed out waiting for RCON readiness." >&2
              sudo docker logs "$CNAME" --tail 200 >&2 || true
              exit 1
            fi
            sleep 5
          done
          EOF
