name: ASA The Island Server Update Workflow (Test Mode)

on:
  push:
    paths:
      - 'ASA/asa-server-1/the_island/docker-compose.yaml'
    branches:
      - main

concurrency:
  group: asa-server-updates
  cancel-in-progress: false

jobs:
  deploy:
    runs-on: self-hosted   # Use your self-hosted runner label here; ensure the runner is online and idle
    timeout-minutes: 60
    env:
      ACTIONS_RUNNER_DEBUG: true   # enable debug logging in runner

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Setup SSH Key
        uses: webfactory/ssh-agent@v0.9.0
        with:
          ssh-private-key: ${{ secrets.ASA_SERVER_1_PRIVATE_KEY }}

            - name: Debug Info
        run: |
          set -x
          echo "Runner labels: ${{ runner.labels }}"
          echo "Branch: $GITHUB_REF"
          echo "Commit SHA: $GITHUB_SHA"
          echo "==> Checking SSH port connectivity via /dev/tcp"
          # Use bash built-in TCP check instead of netcat
          if timeout 5 bash -c "</dev/tcp/${{ secrets.ASA_SERVER_1_SSH_HOST }}/33"; then
            echo "Port 33 is reachable"
          else
            echo "Port 33 is NOT reachable"
            exit 1
          fi

      - name: Send Restart Notification (30 sec warning) (30 sec warning)
        run: |
          set -x
          echo "==> Sending 30s warning to ASA The Island"
          ssh -vvv -o ConnectTimeout=10 -o StrictHostKeyChecking=no -p 33 \
              ${{ secrets.ASA_SERVER_1_SSH_USER }}@${{ secrets.ASA_SERVER_1_SSH_HOST }} \
            "docker exec asa-server-theisland asa-ctrl rcon --exec \"serverchat [TEST] Restarting in 30 seconds for update\""

      - name: Wait 30 seconds before update
        run: |
          set -x
          echo "==> Sleeping for 30s"
          sleep 30

      - name: Save World & Shutdown Notification
        run: |
          set -x
          echo "==> Sending saveworld & shutdown notification"
          ssh -vvv -o ConnectTimeout=10 -o StrictHostKeyChecking=no -p 33 \
              ${{ secrets.ASA_SERVER_1_SSH_USER }}@${{ secrets.ASA_SERVER_1_SSH_HOST }} \
            "docker exec asa-server-theisland asa-ctrl rcon --exec \"serverchat [TEST] Saving world and shutting down for update\" && docker exec asa-server-theisland asa-ctrl rcon --exec \"saveworld\""

      - name: Stop ASA The Island Container
        run: |
          set -x
          echo "==> Stopping container via docker compose down"
          ssh -vvv -o ConnectTimeout=10 -o StrictHostKeyChecking=no -p 33 \
              ${{ secrets.ASA_SERVER_1_SSH_USER }}@${{ secrets.ASA_SERVER_1_SSH_HOST }} \
            "cd ${{ secrets.ASA_SERVER_1_WORK_DIR }}/ASA/asa-server-1/the_island && docker compose down --timeout 30"

      - name: Pull Repo Changes
        run: |
          set -x
          echo "==> Pulling latest changes"
          ssh -vvv -o ConnectTimeout=10 -o StrictHostKeyChecking=no -p 33 \
              ${{ secrets.ASA_SERVER_1_SSH_USER }}@${{ secrets.ASA_SERVER_1_SSH_HOST }} \
            "cd ${{ secrets.ASA_SERVER_1_WORK_DIR }} && git pull origin main"

      - name: Restart The Island Container
        run: |
          set -x
          echo "==> Pulling & restarting container"
          ssh -vvv -o ConnectTimeout=10 -o StrictHostKeyChecking=no -p 33 \
              ${{ secrets.ASA_SERVER_1_SSH_USER }}@${{ secrets.ASA_SERVER_1_SSH_HOST }} \
            "cd ${{ secrets.ASA_SERVER_1_WORK_DIR }}/ASA/asa-server-1/the_island && docker compose pull && docker compose up -d"
